
version: '3.8'
services:
  xander-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # This line tells Docker not to override with host's empty node_modules
    environment:
      - NODE_ENV=production
