
version: "3.8"
services:
  app:
    working_dir: /app
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../../../etc/letsencrypt:/etc/letsencrypt   
    container_name: nginx
    working_dir: /nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    
volumes:
  mongo_data: