
version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: studio_moika_dev
    volumes:
      - ./mongo_data:/data/db
volumes:
  mongo_data: